<img src= 'http://www.bigbang-datascience.com/wp-content/uploads/2017/09/cropped-Logo-01.jpg' width=300/>

# Association Rules - Apriori

In [ ]:
#pip install mlxtend

In [2]:
# Importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mlxtend.frequent_patterns import apriori, association_rules

### Theory of Apriori Algorithm
There are three major components of Apriori algorithm:

  **Support**  
  **Confidence**  
  **Lift**

Suppose we have a record of 1 thousand customer transactions, and we want to find the Support, Confidence, and Lift for two items e.g. burgers and ketchup. Out of one thousand transactions, 100 contain ketchup while 150 contain a burger. Out of 150 transactions where a burger is purchased, 50 transactions contain ketchup as well. Using this data, we want to find the support, confidence, and lift.

**Support**
Support refers to the default popularity of an item and can be calculated by finding number of transactions containing a particular item divided by total number of transactions. Suppose we want to find support for item B. This can be calculated as:

In [ ]:
Support(B) = (Transactions containing (B))/(Total Transactions)

For instance if out of 1000 transactions, 100 transactions contain Ketchup then the support for item Ketchup can be calculated as:

In [ ]:
Support(Ketchup) = (Transactions containingKetchup)/(Total Transactions)
Support(Ketchup) = 100/1000
                 = 10%

**Confidence**  
Confidence refers to the likelihood that an item B is also bought if item A is bought. It can be calculated by finding the number of transactions where A and B are bought together, divided by total number of transactions where A is bought. Mathematically, it can be represented as:

In [ ]:
Confidence(A→B) = (Transactions containing both (A and B))/(Transactions containing A)

Coming back to our problem, we had 50 transactions where Burger and Ketchup were bought together. While in 150 transactions, burgers are bought. Then we can find likelihood of buying ketchup when a burger is bought can be represented as confidence of Burger -> Ketchup and can be mathematically written as:

In [ ]:
Confidence(Burger→Ketchup) = (Transactions containing both (Burger and Ketchup))/(Transactions containing A)

Confidence(Burger→Ketchup) = 50/150
                           = 33.3%

**Lift**  
Lift(A -> B) refers to the increase in the ratio of sale of B when A is sold. Lift(A –> B) can be calculated by dividing Confidence(A -> B) divided by Support(B). Mathematically it can be represented as:

In [ ]:
Lift(A→B) = (Confidence (A→B))/(Support (B))

Coming back to our Burger and Ketchup problem, the Lift(Burger -> Ketchup) can be calculated as:

In [ ]:
Lift(Burger→Ketchup) = (Confidence (Burger→Ketchup))/(Support (Ketchup))

Lift(Burger→Ketchup) = 33.3/10
                     = 3.33

**Lift** basically tells us that the likelihood of buying a Burger and Ketchup together is 3.33 times more than the likelihood of just buying the ketchup. A Lift of 1 means there is no association between products A and B. Lift of greater than 1 means products A and B are more likely to be bought together. Finally, Lift of less than 1 refers to the case where two products are unlikely to be bought together.

### Importing the Dataset
Now let's import the dataset and see what we're working with. Download the dataset and place it in the "Datasets" folder of the "D" drive (or change the code below to match the path of the file on your computer) and execute the following script:

In [3]:
trans = pd.read_csv('Transactions.csv', sep=',', header = None)

In [4]:
print(type(trans))

<class 'pandas.core.frame.DataFrame'>

In [5]:
trans.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7501 entries, 0 to 7500
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       7501 non-null   object
 1   1       5747 non-null   object
 2   2       4389 non-null   object
 3   3       3345 non-null   object
 4   4       2529 non-null   object
 5   5       1864 non-null   object
 6   6       1369 non-null   object
 7   7       981 non-null    object
 8   8       654 non-null    object
 9   9       395 non-null    object
 10  10      256 non-null    object
 11  11      154 non-null    object
 12  12      87 non-null     object
 13  13      47 non-null     object
 14  14      25 non-null     object
 15  15      8 non-null      object
 16  16      4 non-null      object
 17  17      4 non-null      object
 18  18      3 non-null      object
 19  19      1 non-null      object
dtypes: object(20)
memory usage: 1.1+ MB

Each row of the dataset represents items that were purchased together on the same day at the same store.The dataset is a sparse dataset as relatively high percentage of data is NA or NaN or equivalent.
These NaNs make it hard to read the table. Let’s find out how many unique items are actually there in the table.

In [21]:
items = (trans[0].unique())
items

array(['shrimp', 'burgers', 'chutney', 'turkey', 'mineral water',
       'low fat yogurt', 'whole wheat pasta', 'soup', 'frozen vegetables',
       'french fries', 'eggs', 'cookies', 'spaghetti', 'meatballs',
       'red wine', 'rice', 'parmesan cheese', 'ground beef',
       'sparkling water', 'herb & pepper', 'pickles', 'energy bar',
       'fresh tuna', 'escalope', 'avocado', 'tomato sauce',
       'clothes accessories', 'energy drink', 'chocolate',
       'grated cheese', 'yogurt cake', 'mint', 'asparagus', 'champagne',
       'ham', 'muffins', 'french wine', 'chicken', 'pasta', 'tomatoes',
       'pancakes', 'frozen smoothie', 'carrots', 'yams', 'shallot',
       'butter', 'light mayo', 'pepper', 'candy bars', 'cooking oil',
       'milk', 'green tea', 'bug spray', 'oil', 'olive oil', 'salmon',
       'cake', 'almonds', 'salt', 'strong cheese', 'hot dogs', 'pet food',
       'whole wheat rice', 'antioxydant juice', 'honey', 'sandwich',
       'salad', 'magazines', 'protein bar', 'mayonnaise', 'cider',
       'burger sauce', 'green grapes', 'vegetables mix', 'bramble',
       'nonfat milk', 'tomato juice', 'green beans', 'strawberries',
       'eggplant', 'mushroom cream sauce', 'gums', 'cereals', 'flax seed',
       'spinach', 'soda', 'dessert wine', 'corn', 'fresh bread',
       'brownies', 'fromage blanc', 'chocolate bread', 'mashed potato',
       'gluten free bar', 'cottage cheese', 'whole weat flour', 'chili',
       'barbecue sauce', 'light cream', 'mint green tea', 'black tea',
       'bacon', 'shampoo', 'blueberries', 'cauliflower',
       'extra dark chocolate', 'white wine', 'babies food', 'toothpaste',
       'melons', 'ketchup', 'cream', 'hand protein bar', 'body spray',
       'oatmeal'], dtype=object)

In [22]:
len(items)

115

### Data Preprocessing
To make use of the apriori module given by mlxtend library, we need to convert the dataset according to it’s liking. apriori module requires a dataframe that has either 0 and 1 or True and False as data. The data we have is all string (name of items), we need to One Hot Encode the data.

Custom One Hot Encoding

### One Hot Encoding

In [23]:
encoded_vals = []
for index, row in trans.iterrows():  #Iterate over DataFrame rows as (index, Series) pairs.
    labels = {}
    uncommons = list(set(items) - set(row))
    commons = list(set(items).intersection(row)) # Return a set that contains the items that exist in both set x, and set y:
    for uc in uncommons:
        labels[uc] = 0
    for com in commons:
        labels[com] = 1
    encoded_vals.append(labels)
encoded_vals[0]
ohe_trans = pd.DataFrame(encoded_vals)

In [24]:
encoded_vals[1]

{'salmon': 0,
 'cooking oil': 0,
 'oil': 0,
 'ground beef': 0,
 'hot dogs': 0,
 'honey': 0,
 'tomato sauce': 0,
 'sandwich': 0,
 'whole wheat rice': 0,
 'chili': 0,
 'energy drink': 0,
 'gluten free bar': 0,
 'gums': 0,
 'yogurt cake': 0,
 'fromage blanc': 0,
 'milk': 0,
 'cereals': 0,
 'light mayo': 0,
 'strawberries': 0,
 'frozen vegetables': 0,
 'french wine': 0,
 'cake': 0,
 'blueberries': 0,
 'whole wheat pasta': 0,
 'brownies': 0,
 'carrots': 0,
 'pickles': 0,
 'strong cheese': 0,
 'cider': 0,
 'mint green tea': 0,
 'cauliflower': 0,
 'rice': 0,
 'nonfat milk': 0,
 'herb & pepper': 0,
 'mushroom cream sauce': 0,
 'body spray': 0,
 'soda': 0,
 'toothpaste': 0,
 'shampoo': 0,
 'salt': 0,
 'pancakes': 0,
 'vegetables mix': 0,
 'parmesan cheese': 0,
 'chutney': 0,
 'fresh bread': 0,
 'extra dark chocolate': 0,
 'dessert wine': 0,
 'shrimp': 0,
 'bacon': 0,
 'magazines': 0,
 'whole weat flour': 0,
 'fresh tuna': 0,
 'light cream': 0,
 'candy bars': 0,
 'muffins': 0,
 'yams': 0,
 'white wine': 0,
 'cookies': 0,
 'oatmeal': 0,
 'almonds': 0,
 'bramble': 0,
 'barbecue sauce': 0,
 'cream': 0,
 'bug spray': 0,
 'olive oil': 0,
 'mineral water': 0,
 'spinach': 0,
 'butter': 0,
 'energy bar': 0,
 'frozen smoothie': 0,
 'mayonnaise': 0,
 'chocolate bread': 0,
 'mashed potato': 0,
 'soup': 0,
 'mint': 0,
 'protein bar': 0,
 'clothes accessories': 0,
 'eggplant': 0,
 'cottage cheese': 0,
 'pasta': 0,
 'green beans': 0,
 'black tea': 0,
 'burger sauce': 0,
 'flax seed': 0,
 'hand protein bar': 0,
 'pepper': 0,
 'babies food': 0,
 'antioxydant juice': 0,
 'salad': 0,
 'champagne': 0,
 'sparkling water': 0,
 'chicken': 0,
 'turkey': 0,
 'escalope': 0,
 'corn': 0,
 'avocado': 0,
 'shallot': 0,
 'ham': 0,
 'green tea': 0,
 'red wine': 0,
 'french fries': 0,
 'green grapes': 0,
 'low fat yogurt': 0,
 'tomato juice': 0,
 'asparagus': 0,
 'chocolate': 0,
 'grated cheese': 0,
 'pet food': 0,
 'tomatoes': 0,
 'spaghetti': 0,
 'ketchup': 0,
 'melons': 0,
 'burgers': 1,
 'eggs': 1,
 'meatballs': 1}

In [25]:
encoded_vals[0]

{'cooking oil': 0,
 'oil': 0,
 'ground beef': 0,
 'hot dogs': 0,
 'tomato sauce': 0,
 'sandwich': 0,
 'whole wheat rice': 0,
 'chili': 0,
 'gluten free bar': 0,
 'gums': 0,
 'yogurt cake': 0,
 'fromage blanc': 0,
 'milk': 0,
 'cereals': 0,
 'light mayo': 0,
 'strawberries': 0,
 'frozen vegetables': 0,
 'french wine': 0,
 'cake': 0,
 'blueberries': 0,
 'whole wheat pasta': 0,
 'brownies': 0,
 'carrots': 0,
 'pickles': 0,
 'strong cheese': 0,
 'cider': 0,
 'mint green tea': 0,
 'cauliflower': 0,
 'rice': 0,
 'nonfat milk': 0,
 'herb & pepper': 0,
 'mushroom cream sauce': 0,
 'meatballs': 0,
 'body spray': 0,
 'soda': 0,
 'toothpaste': 0,
 'shampoo': 0,
 'salt': 0,
 'pancakes': 0,
 'parmesan cheese': 0,
 'chutney': 0,
 'fresh bread': 0,
 'extra dark chocolate': 0,
 'dessert wine': 0,
 'bacon': 0,
 'magazines': 0,
 'fresh tuna': 0,
 'light cream': 0,
 'candy bars': 0,
 'muffins': 0,
 'white wine': 0,
 'cookies': 0,
 'oatmeal': 0,
 'burgers': 0,
 'bramble': 0,
 'barbecue sauce': 0,
 'cream': 0,
 'bug spray': 0,
 'butter': 0,
 'energy bar': 0,
 'mayonnaise': 0,
 'chocolate bread': 0,
 'mashed potato': 0,
 'soup': 0,
 'mint': 0,
 'protein bar': 0,
 'clothes accessories': 0,
 'eggplant': 0,
 'pasta': 0,
 'green beans': 0,
 'black tea': 0,
 'burger sauce': 0,
 'flax seed': 0,
 'hand protein bar': 0,
 'pepper': 0,
 'babies food': 0,
 'champagne': 0,
 'sparkling water': 0,
 'chicken': 0,
 'turkey': 0,
 'escalope': 0,
 'corn': 0,
 'shallot': 0,
 'ham': 0,
 'red wine': 0,
 'french fries': 0,
 'eggs': 0,
 'asparagus': 0,
 'chocolate': 0,
 'grated cheese': 0,
 'pet food': 0,
 'tomatoes': 0,
 'spaghetti': 0,
 'ketchup': 0,
 'melons': 0,
 'salmon': 1,
 'honey': 1,
 'olive oil': 1,
 'mineral water': 1,
 'energy drink': 1,
 'spinach': 1,
 'frozen smoothie': 1,
 'cottage cheese': 1,
 'antioxydant juice': 1,
 'salad': 1,
 'avocado': 1,
 'green tea': 1,
 'green grapes': 1,
 'vegetables mix': 1,
 'low fat yogurt': 1,
 'tomato juice': 1,
 'shrimp': 1,
 'whole weat flour': 1,
 'yams': 1,
 'almonds': 1}

In [26]:
ohe_trans

,cooking oil,oil,ground beef,hot dogs,tomato sauce,sandwich,whole wheat rice,chili,gluten free bar,gums,...,avocado,green tea,green grapes,vegetables mix,low fat yogurt,tomato juice,shrimp,whole weat flour,yams,almonds
0,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7497,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
7498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7499,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
7500,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

# Applying Apriori - Working with Sparse Representations

apriori module from mlxtend library provides fast and efficient apriori implementation.

__Parameters__

__df__ : One-Hot-Encoded DataFrame or DataFrame that has 0 and 1 or True and False as values
__min_support__ : Floating point value between 0 and 1 that indicates the minimum support required for an itemset to be selected.  

of observation with item / total observation# of observation with item / total observation

__use_colnames__ : This allows to preserve column names for itemset making it more readable.
__max_len__ : Max length of itemset generated. If not set, all possible lengths are evaluated.
__verbose__ : Shows the number of iterations if >= 1 and low_memory is True. If =1 and low_memory is False , shows the number of combinations.

__low_memory__ :
If True, uses an iterator to search for combinations above min_support. Note that while low_memory=True should only be used for large dataset if memory resources are limited, because this implementation is approx. 3–6x slower than the default.

In [32]:
freq_items = apriori(ohe_trans,
                     min_support=0.02, 
                     use_colnames=True, 
                     verbose=1)
freq_items

Processing 855 combinations | Sampling itemset size 3

C:\Users\sohni\anaconda3\envs\mlenv\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:115: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  DeprecationWarning,

      support                          itemsets
0    0.051060                     (cooking oil)
1    0.023064                             (oil)
2    0.098254                     (ground beef)
3    0.032396                        (hot dogs)
4    0.058526                (whole wheat rice)
..        ...                               ...
98   0.027596        (olive oil, mineral water)
99   0.020264  (frozen smoothie, mineral water)
100  0.031063        (green tea, mineral water)
101  0.023997   (low fat yogurt, mineral water)
102  0.023597           (shrimp, mineral water)

[103 rows x 2 columns]

### Applying Association Rules

The next step is to apply the Association Rules algorithm on the dataset. To do so, we can use the Association Rules class that we imported from the Association Rules library.   

The Association Rules class requires some parameter values to work. The first parameter is the list of list that you want to extract rules from. The second parameter is the min_support parameter. This parameter is used to select the items with support values greater than the value specified by the parameter. Next, the min_confidence parameter filters those rules that have confidence greater than the confidence threshold specified by the parameter. Similarly, the min_lift parameter specifies the minimum lift value for the short listed rules. Finally, the min_length parameter specifies the minimum number of items that you want in your rules.   

Let's suppose that we want rules for only those items that are purchased at least 5 times a day, or 7 x 5 = 35 times in one week, since our dataset is for a one-week time period. The support for those items can be calculated as 35/7500 = 0.0045. The minimum confidence for the rules is 20% or 0.2. Similarly, we specify the value for lift as 3 and finally min_length is 2 since we want at least two products in our rules. These values are mostly just arbitrarily chosen, so you can play with these values and see what difference it makes in the rules you get back out.

Execute the following script:

In [40]:
# Metric can be set to confidence, lift, support, leverage and conviction.

rules = association_rules(freq_items, 
                          metric="confidence", 
                          min_threshold=0.3)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(cooking oil),(mineral water),0.051060,0.238368,0.020131,0.394256,1.653978,0.007960,1.257349
1,(ground beef),(spaghetti),0.098254,0.174110,0.039195,0.398915,2.291162,0.022088,1.373997
2,(ground beef),(mineral water),0.098254,0.238368,0.040928,0.416554,1.747522,0.017507,1.305401
3,(whole wheat rice),(mineral water),0.058526,0.238368,0.020131,0.343964,1.442993,0.006180,1.160960
4,(milk),(mineral water),0.129583,0.238368,0.047994,0.370370,1.553774,0.017105,1.209650

In the second line here we convert the rules found by the apriori class into a list since it is easier to view the results in this form.

### Viewing the Results
Let's first find the total number of rules mined by the apriori class. Execute the following script:

In [44]:
print(len(rules))

20

### Visualizing results

__1. Support vs Confidence__

In [ ]:
plt.scatter(rules['support'], rules['confidence'], alpha=0.5)
plt.xlabel('support')
plt.ylabel('confidence')
plt.title('Support vs Confidence')
plt.show()

__2. Support vs Lift__

In [ ]:
plt.scatter(rules['support'], rules['lift'], alpha=0.5)
plt.xlabel('support')
plt.ylabel('lift')
plt.title('Support vs Lift')
plt.show()

__3. Lift vs Confidence__

In [ ]:
fit = np.polyfit(rules['lift'], rules['confidence'], 1)
fit_fn = np.poly1d(fit)
plt.plot(rules['lift'], rules['confidence'], 'yo', rules['lift'], 
 fit_fn(rules['lift']))

# Applying Apriori - as a list

The Apriori library we are going to use requires our dataset to be in the form of a list of lists, where the whole dataset is a big list and each transaction in the dataset is an inner list within the outer big list. Currently, we have data in the form of a pandas data frame. To convert our pandas data frame into a list of lists, execute the following script:

In [ ]:
# Create the sparsity Matrix using the fo loop
transactions = []
for i in range(0, 7501):
    transactions.append([str(trans.values[i,j]) for j in range(0, 20)]) # Transforming to string

In [ ]:
#pip install apyori
from apyori import apriori

In [ ]:
print(type(transactions))

In [ ]:
transactions

In [ ]:
len(transactions)

In [ ]:
transactions[0]

In [ ]:
transactions[-1]

### Implementing Apriori
We can now specify the parameters of the apriori class.  
__The List__  
__min_support__  
__min_confidence__  
__min_lift__  
__min_length (the minimum number of items that you want in your rules, typically 2)__ 

Let’s suppose that we want only items that are purchased at least 40 times in a month. The support for those items can be calculated as 40/7500 = 0.0053. The minimum confidence for the rules is 20% or 0.2. Similarly, we specify the value for lift as 3 and finally, min_length is 2 since we want at least two products in our rules. These values are mostly just arbitrarily chosen and they need to be fine-tuned empirically.

In [ ]:
association_rules = apriori(transactions, min_support = 0.0053, min_confidence=0.2, min_lift=3, min_length = 3)
results = list(association_rules)

In [ ]:
results[0]

In [ ]:
for result in results[:10]:
    items = result[0]
    items = [x for x in items]
    print('Rule: ' + items[0] + '  --> ' + items[1])
    print('Support {:.4f}'.format(result[1]))
    print('Confidence {:.4f}'.format(float(result[2][0][2])))
    print('Lift {:.4f}'.format(result[2][0][3]))
    print('============\n')

In [ ]:
# Visualising the results
# results = list(rules)
list(results)